Repository elastic/gosigar, pull requests merged in 2018-03, with the labels that each got.

#97 Add support for huge TLB pages on Linux
  CHANGELOG.md
  README.md
  concrete_sigar.go
  sigar_darwin.go
  sigar_freebsd.go
  sigar_interface.go
  sigar_linux.go
  sigar_linux_common.go
  sigar_linux_test.go
  sigar_openbsd.go
  sigar_stub.go
  sigar_windows.go
Labels: enhancement, review

#101 Changelog for 0.9.0
  CHANGELOG.md
Labels: review

#104 Add missing runtime import for FreeBSD
  CHANGELOG.md
  sigar_freebsd.go
Labels: bug

#103 Recover as workaround for panic when reading proc files
  sigar_linux_common.go
Labels: bug, review
