Repository elastic/gosigar, pull requests merged in 2020-07, with the labels that each got.

#139 Remove dependency on gotestcover
  .appveyor.yml
  .travis.yml
Labels: review

#140 Ignore unsafe pointer conversion warning
  CHANGELOG.md
  sigar_util.go
Labels: bug, review

#141 fix odd array to string function
  CHANGELOG.md
  sigar_darwin.go
  sigar_openbsd.go
  sigar_util.go
  sigar_util_test.go
Labels: bug

#142 Close v0.11.0 Changelog
  CHANGELOG.md
Labels: review
