Repository elastic/gosigar, pull requests merged in 2021-02, with the labels that each got.

#154 ci: JJBB job definition
  .ci/jobs/defaults.yml
  .ci/jobs/main.yml
Labels: ci, enhancement, team:automation

#152 Add M1 support
  CHANGELOG.md
  sigar_common_darwin.go
  sigar_darwin.go
  sigar_darwin_amd64.go
Labels: bug

#156 [CI] add badge
  README.md
Labels: ci
